### ISSUE TITLE
Can't launch lidar_centerpoint with error: could not load library: libcenterpoint_cuda_libraries.so.

### ISSUE THREAD

**Issue by mikechan0731** [autowarefoundation/autoware.universe#1256]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

I use a custom docker image and want to try using ros2 lidar_centerpoint.
It has been successfully established so far, but when using ros2 launch, the following error occurs.
![圖片](https://user-images.githubusercontent.com/10561543/172583688-04e806d8-41b1-4e18-965c-c15437eea21c.png)

### Expected behavior

Hope to use point cloud data for object recognition.

### Actual behavior

Make sure that the docker command has read the gpu.
The instructions are as follows:
```
docker run --user $(id -u):$(id -g) --rm -it  --gpus all -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1 -e XAUTHORITY=/tmp/.dockerjwzszsxi.xauth -v /tmp/.dockerjwzszsxi.xauth:/tmp/.dockerjwzszsxi.xauth -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro autoware-universe-ros2-export:v1 /bin/bash
```

### Steps to reproduce

Nvidia-smi

### Versions

Docker Link: https://drive.google.com/file/d/1sqpyMhZeLFWqCIbepB8lhlv8140bbxac/view?usp=sharing
OS: Ubuntu 20.04
ROS2 Galatic

**Comment by Sharrrrk** [comment]
Can you try to rebuild the lidar_centerpoint package by removing the built targets in /build and /install, and also to make sure that the version of CUDA version in docker is same with local system.

**Comment by xmfcx** [comment]
@mikechan0731 do you have any updates?

**Comment by mitsudome-r** [comment]
@mikechan0731 has tried rebuilding the stack and still had the issue. However, he decided to use the default Autoware docker to avoid the issue. We will close this issue until someone else faces similar issue with his/her custom docker image.

**Comment by HaoruXue** [comment]
@mitsudome-r I have the same issue with custom environment (Nvidia NGC TensorRT container with tensorrt 8.4.1-1+cuda11.6).

I fixed the issue by adding the following to `CMakeLists.txt`

```
  install(
    TARGETS
      centerpoint_cuda_lib
  )
```

You can find the commit [here](https://github.com/airacingtech/autoware.universe/commit/86a0f4fab9fd093f65f2373e8c2906af1d5ffcad).

It turns out `libcenterpoint_cuda_libraries.so` is built in the build/lidar_centerpoint folder but never installed to the install/lidar_centerpoint folder. I am curious as to why this woud work on some version of CUDA and tensorrt as it seems to be CMake issue. `tensorrt_yolo` for example as a same line that installs its built CUDA library: 

https://github.com/autowarefoundation/autoware.universe/blob/main/perception/tensorrt_yolo/CMakeLists.txt#L192

I suggest reopen this issue and see if there are other reasons causing this. Otherwise the example commit above would be the fix.

**Comment by yukke42** [comment]
close this issue since this error is fixed in the PR <https://github.com/autowarefoundation/autoware.universe/pull/1916>.
