### ISSUE TITLE
behavior_path_planner generated path outside of drivable area

### ISSUE THREAD

**Issue by beyzanurkaya** [autowarefoundation/autoware.universe#1761]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

If you give to EGO a goal pose a bit inclined , the path is still generated without considering of the width and length of EGO. And this generated path is outside the drivable area.

![Screenshot from 2022-09-01 10-32-23](https://user-images.githubusercontent.com/32412808/187857957-b21fd5ea-3edc-4535-b7cb-a8e57e149a42.png)

![Screenshot from 2022-09-01 10-34-16](https://user-images.githubusercontent.com/32412808/187858252-6e998e9d-04b2-4caf-a043-5cdf05e4d950.png)

### Expected behavior

If the path to generated is outside the drivable area, the node should not create any path.

### Actual behavior

`behavior_path_planner` creates a path even if the path is outside the drivable area.

![Screenshot from 2022-09-01 10-34-16](https://user-images.githubusercontent.com/32412808/187858318-b99c0359-9597-4a64-876d-9476b5ed3904.png)

### Steps to reproduce

1. Download [1761.zip](https://github.com/autowarefoundation/autoware.universe/files/9469885/1761.zip)
2. Change pcd and lanelet2 maps file path in yaml file
3. run `ros2 launch scenario_test_runner scenario_test_runner.launch.py sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle \
scenario:=/scenario/path/1761.yaml \
architecture_type:=awf/universe launch_rviz:=false launch_autoware:=true`

4. Add ` /planning/scenario_planning/lane_driving/trajectory` topic in rviz

5. When you run the scenario, path occurred outside drivable area.

**Comment by takayuki5168** [comment]
@beyzanurkaya Thank you for your report.
That is because of smooth goal connection in behavior_path_planner.
https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/#smooth-goal-connection

behavior_path_planner does not thoroughly consider if the path is inside the lane or not. Sometimes the path from the behavior_path_planner is outside the lanes with a tight right/left turn on a bit narrow road.
To make the path/trajectory inside the lanes (what we call drivable area) is the role of motion planner (obstacle_avoidance_planner).

Therefore, IMO, I think no code change is required for the issue. What do you think.

**Comment by takayuki5168** [comment]
If you want, I agree with implementing the function to reject the goal if it's near to the lane boundaries and the angle is weird like in your figure in mission_planner.

**Comment by beyzanurkaya** [comment]
I think it makes sense to adding a reject.  because as the vehicle tries to reach this point, a strange trajector occurs at the end of the goal position.

**Comment by beyzanurkaya** [comment]
![Screenshot from 2022-09-06 10-34-20](https://user-images.githubusercontent.com/32412808/188575837-618dcbed-ccee-4ec8-8176-f5c59ca09bb1.png)

**Comment by mehmetdogru** [comment]
@takayuki5168 

Thank you for your comments.

Is there a reason why we are excepting a goal which its orientation is not aligned with the road lanelet center line whether it is close to the lane boundaries or not?

My proposal is that any goal which is not aligned with the related lanelet center line should be discarded. What is your opinion about this?

**Comment by mitsudome-r** [comment]
@mehmetdogru Currently, it is already rejecting the pose with an angle larger than 45 degrees against the direction of the goal lane. 

I could think of two solutions:
* make this a configurable parameter, or
* modify the mission_planning so that it will overwrite the goal pose with lane angle

 @TakaHoribe Any suggestions?

**Comment by mehmetdogru** [comment]
@mitsudome-r 

I am on the side of making `th_angle` a config param.
https://github.com/autowarefoundation/autoware.universe/blob/37e8c99425bffff076d0ec2bf302a8a63a3392a6/planning/mission_planner/src/mission_planner_lanelet2/mission_planner_lanelet2.cpp#L210

I can create a PR about it if everybody is ok with it?
@TakaHoribe @mitsudome-r

**Comment by takayuki5168** [comment]
@mehmetdogru 
Only with the angle constraint, we still will get an invalid goal since there is almost no constraint for the lateral position of the goal.
Therefore the path from behavior path planner may be out of the drivable area. Is it ok for you?

What I meant by rejecting function is, in addition to the current angle constraint, kind of checking if the vehicle footprint with the goal pose is inside the lane or not.

**Comment by mehmetdogru** [comment]
@takayuki5168 

> Only with the angle constraint, we still will get an invalid goal since there is almost no constraint for the lateral position of the goal.

> What I meant by rejecting function is, in addition to the current angle constraint, kind of checking if the vehicle footprint with the goal pose is inside the lane or not.

Yes we will however having the check if vehicle footprint will be inside the lane or not when it is on the goal pose would prevent [`behavior_path_planner/pull_over`](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/#pull-over) working properly I am afraid. Isn't that so?

> Therefore the path from behavior path planner may be out of the drivable area. Is it ok for you?

So since it is a design related topic about behavior_path_planner we can leave it that way for now.



> Anyway I agree to have a parameter for `th_angle`

I guess I will go ahead and create a PR about it then.

**Comment by takayuki5168** [comment]
@mehmetdogru 
> would prevent [behavior_path_planner/pull_over](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/#pull-over) working properly

I think there is no problem. There is a road shoulder lane in lanelet map for pull over. That means the vehicle footprint with the goal pose for pull over is inside the lane.
Is this what you are worrying about?

**Comment by mehmetdogru** [comment]
@takayuki5168 

Yes that was my worry, thank you :) Then there is no problem checking also the vehicle footprint for goal pose. Then there will be 2 PRs related to this topic for `mission_planner`:

1) make `th_angle` a conf param
2) check vehicle footprint for goal pose and reject if it is outside of the lane boundaries

Do you agree with this?

**Comment by mitsudome-r** [comment]
@takayuki5168 Do you have any concerns with @mehmetdogru 's idea? At least, they look reasonable to me.

**Comment by xmfcx** [comment]
@takayuki5168 friendly ping

**Comment by mitsudome-r** [comment]
@mehmetdogru Are you planning to create a PR for the fix, or would you like someone else to do it?

**Comment by mehmetdogru** [comment]
@mitsudome-r 

Sorry for the late reply. We were very busy with the field tests for some time, so couldn't work on some of the issues. 

Yes, I can create a PR about this issue this week.

**Comment by ismetatabay** [comment]
@mehmetdogru I created the PR that checks the footprint of the goal and added the th_angle parameter. I'm a bit confused for the parameter part. I defined a parameter struct in the header, considering the future case of adding parameters to the ```mission_planner```. If this is not needed, I can remove that struct and declare it as a variable single parameter.

**Comment by mehmetdogru** [comment]
> I created the PR that checks the footprint of the goal and added the th_angle parameter. I'm a bit confused for the parameter part. I defined a parameter struct in the header, considering the future case of adding parameters to the `mission_planner`. If this is not needed, I can remove that struct and declare it as a variable single parameter.

@ismetatabay

Thanks for working on this.

I would keep it local and declare the struct in `mission_planner_lanelet2.hpp`. You can rename the struct accordingly.

**Comment by takayuki5168** [comment]
FYI: There will be a large change on mission_planner, so it may be better to create a PR based on this branch.
https://github.com/autowarefoundation/autoware.universe/pull/1495

**Comment by ismetatabay** [comment]
@takayuki5168 @mehmetdogru  Hi, Should I wait for #1495 to merge to avoid conflicts?

**Comment by xmfcx** [comment]
This is being worked on: https://github.com/autowarefoundation/autoware.universe/pull/2088

**Comment by BonoloAWF** [comment]
> 

@xmfcx  should this issue be closed then?

**Comment by BonoloAWF** [comment]
> This is being worked on: #2088

@xmfcx should this issue be closed then?

**Comment by mehmetdogru** [comment]
> > This is being worked on: #2088
> 
> @xmfcx should this issue be closed then?

@BonoloAWF it will be closed automatically once #2088 is merged since they are linked.

**Comment by BonoloAWF** [comment]
Thanks @mehmetdogru. Moved to next milestone since the PR looks to be ongoing.
