### ISSUE TITLE
Add vehicle control command message to AD API

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware.universe#3787]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Right now Autoware publishes `/control/command/control_cmd: autoware_control_msgs/msg/Control` in [control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp](https://github.com/autowarefoundation/autoware.universe/blob/a3ce54a7fc13175e968f2951af8750fff321b622/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp#L411) to control the vehicle.

This issue aims to instead, publish a standardized AD API message.

### Purpose

Internal messaging API shouldn't affect how outside platforms (simulators, vehicles) interface with the Autoware.

While working on this task: https://github.com/autowarefoundation/autoware.universe/pull/3677#issuecomment-1553295788 I've realized we are using autoware_auto_control_msgs for the:
- https://github.com/tier4/scenario_simulator_v2
- https://github.com/tier4/AWSIM

And with @mitsudome-r 's guidance, agreed that it's a better idea to use the AD API interface to update them.

### Possible approaches

Explained in **Definition of done** section below.

### Definition of done

- [ ] Raise this in Planning and Control WG
- [ ] Create a new message for Autoware's final output for the control command.
  - [ ] Create the message in https://github.com/autowarefoundation/autoware_adapi_msgs
- [ ] Publish it in an appropriate part of https://github.com/autowarefoundation/autoware.universe/tree/main/system/default_ad_api
  - [ ] Create the PR in https://github.com/autowarefoundation/autoware.universe

**Comment by xmfcx** [comment]
cc. @TakaHoribe @takayuki5168 @mehmetdogru @brkay54 @isamu-takagi @yukkysaito @mitsudome-r

**Comment by isamu-takagi** [comment]
@xmfcx Thank you for the suggestion. I agree with "Option A - Use autoware_msgs" and suggest the following for the disadvantages. There are two features.
- Separate message package into public and private parts for each component.
- Separate message definition by rosidl and interface definition.

> Dependency: If there are significant changes in the future versions of autoware_msgs or if they are deprecated, it might affect the simulator side.

The component interface is the public part of the messages for each component. The current update frequency is a little high, but ideally stability is required.  You are concerned about the impact on the simulator, but changing the component interface will affect all implementation of that component such as vehicle drivers and sensor drivers. The simulator works as a kind of driver, so we don't need to think about the simulator specially. If the public part becomes clear, the update frequency should decrease. Mandatory changes are handled by type adaptation described later.

> Possible Inefficiency: If autoware_msgs contains data fields or structures that aren't necessary for the particular simulator integration, it could introduce inefficiencies in communication.

This should be resolved by separating the public and private parts of the message. Unnecessary data should probably be moved to private messages. Since the simulator performs by replacing some components such as vehicle and sensing, it is necessary to support the same interface as those components.

![component-interface-scope](https://github.com/autowarefoundation/autoware.universe/assets/43976882/c2b46b92-0ea6-46dd-b3cd-5b577a6f7e7f)

> Versioning Complexity: If different versions of autoware_msgs are used in different parts of the project, it can cause confusion and potential errors.

Message definitions by rosidl include a serialization layer. If you convert to JSON like rosbridge, you can communicate if the fields are the same, but if you are communicating with DDS using rclcpp or rclpy, communication cannot be guaranteed if messages of different versions are mixed because its binary format may not be the same.

One solution is to separate message definition/serialization by rosidl and interface definition using [type adaptation](https://ros.org/reps/rep-2007.html). This way, we can safely use multiple versions of the interface because only the latest message is used for serialization even if the message type changes. 

![component-interface-adaption](https://github.com/autowarefoundation/autoware.universe/assets/43976882/6a202645-27c1-47f4-ad6c-e9fb91703ad4)

**Comment by xmfcx** [comment]
@isamu-takagi thanks for the comprehensive suggestion you've provided.

To start simple, I've created following issue:
- 

> One solution is to separate message definition/serialization by rosidl and interface definition using [type adaptation](https://ros.org/reps/rep-2007.html).

I should investigate the type adaptation rep thoroughly and then I can also add my thoughts about your proposal.

Is it OK to write a simple converter-publisher node?

And we can consider your proposal in a new issue, where we can discuss about the versioning `autoware_msgs`.
- I will create this issue today.

I am closing this issue for now, we can discuss versioning in detail in the new issue, you can also copy your message there.
