### ISSUE TITLE
Tensorrt_yolo issue in autoware universe

### ISSUE THREAD

**Issue by xmfcx** [autowarefoundation/autoware.universe#918]
### Discussed in https://github.com/orgs/autowarefoundation/discussions/229

<div type='discussions-op-text'>

<sup>Originally posted by **amtommy** April 26, 2022</sup>
Hello! 
I tried to run the tensorrt_yolo, but I got the incorrect detection results. (see [figure](https://drive.google.com/file/d/1tUNgs4lruQ_18EGAlDkF4ar3d-EDBPut/view?usp=sharing)) 
How to fix it?

Thank you! </div>

**Comment by kaancolak** [comment]
@amtommy I tested YoloV3, YoloV4, and YoloV5l with the bag file provided by you. It looks like working well without any change current codebase. 

Could you share your steps for reproducing your detection results?

I shared result videos:

YOLO V5L:
[![Img alt text](https://img.youtube.com/vi/0Bn--EdFYf4/0.jpg)](https://youtu.be/0Bn--EdFYf4)

YOLO V4:
[![Img alt text](https://img.youtube.com/vi/BYIpBOyf8Yg/0.jpg)](https://youtu.be/BYIpBOyf8Yg)

YOLO V3:
[![Img alt text](https://img.youtube.com/vi/IEw1yTzKhlI/0.jpg)](https://youtu.be/IEw1yTzKhlI)

**Comment by amtommy** [comment]
@kaancolak  Thanks for your verification.
I compare my code with the current codebase.
I find the problem is the module uses the default anchor size[[link](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/tensorrt_yolo/src/nodelet.cpp#L57)], so I got the incorrect result.
Now I use the correct anchor size [[link](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/tensorrt_yolo/config/yolov3.param.yaml#L4)], and I get the same result as yours.
The problem is solved, thanks for your help.
