### ISSUE TITLE
Yaw calculation is unstable in obstacle_avoidance_planner when skipping optimization.

### ISSUE THREAD

**Issue by takayuki5168** [autowarefoundation/autoware.universe#966]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

We can skip optimization in obstacle_avoidance_planner (then, just resample path from behavior module).
In this condition, yaw calculation is unstable and this causes some failure in other modules (e.g. detection area in obstacle stop planner is expanded, and it detects obstacles outside the trajectory, then do stop planning).

### Expected behavior

Yaw calculation is stable

### Actual behavior

Yaw calculation is unstable

### Steps to reproduce

1. fix yaw calculation algorithm

**Comment by kosuke55** [comment]
skip_optimization=false
![image](https://user-images.githubusercontent.com/39142679/170422564-8ee1801b-9d3f-4e56-ae0a-fd7bc91966fc.png)
skip_optimization=true
![image](https://user-images.githubusercontent.com/39142679/170422534-17c98e80-e719-4213-8f23-76c511da5b30.png)

**Comment by takayuki5168** [comment]
thanks
cc @tkimura4

**Comment by mitsudome-r** [comment]
@takayuki5168 Do you already have an idea how to fix the issue? If you are planning to work on this tasks, please assign yourself as assignee. Otherwise, please attach help-wanted tag so that we can assign someone else to look into this.

**Comment by takayuki5168** [comment]
@mitsudome-r I don't look into this issue, so I have no idea so far. I attached help-wanted.
Let me say again that this issue will not occur with the default setting (skip_optimization = false in obstacle_avoidance_planner)

**Comment by mitsudome-r** [comment]
I have assigned @mehmetdogru so that he can investigate when he has time. Any other help is appreciated.

**Comment by xmfcx** [comment]
@klu17 will look into this.

**Comment by mitsudome-r** [comment]
@takayuki5168 Could you provide the steps to reproduce the error (including sharing maps, scenarios that you used to find the error)

**Comment by kosuke55** [comment]
@mitsudome-r @takayuki5168 
Any map(like [sample](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/#steps)) can be used, just set skip_optimization to true(use rqt_reconfigure or edit launch file) and draw a path with curves. 
https://user-images.githubusercontent.com/39142679/174250077-60972945-280d-4340-a043-5257bd48b232.mp4

**Comment by mitsudome-r** [comment]
Steps to reproduce:
* Follow [installation](https://autowarefoundation.github.io/autoware-documentation/main/installation/#installing-autoware) instruction to install Autoware
* Follow [planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/#planning-simulation) instructions to download the sample map and launch planning simulator.
* Set current pose and goal pose as shown in the image.
![image](https://user-images.githubusercontent.com/43976834/176368298-7ee7306c-22a4-4a08-af81-efe6b634d71d.png)
* In rviz display, turn on the debug marker in Planning->ScenarioPlanning->LaneDriving->MotionPlanning->DebugMarker. This will visualize the footprint of the vehicle on the trajectory
![image](https://user-images.githubusercontent.com/43976834/176369089-dc6f29f3-bc60-4195-955a-33f5e2aa347c.png)

* start rqt_reconfigure 
```
source autoware/install/setup.bash
ros2 run rqt_reconfigure rqt_reconfigure
```
* Type obstacle_avoidance in the filter key and expand to go to the configuration window for the `obstacle_avoidance_planner` node.
* tick/untick option.skip_optimization and confirm that footprint is not smooth when skip_optimization is on.
 
![image](https://user-images.githubusercontent.com/43976834/176369521-7f52d96d-322a-4fcc-8622-6a3f85c41590.png)

**Comment by mitsudome-r** [comment]
@klu17 Do you have any updates on this issue?

**Comment by klu17** [comment]
No, I don't. I'll unassign.

**Comment by angry-crab** [comment]
It seems that when optimization is skipped, the output is simply the path message being received. `obstacle_avoidance_planner` does nothing to the planned path. I'll investigate further.

**Comment by takayuki5168** [comment]
@angry-crab 
obstacle avoidance planner does resampling of x, y, and yaw to the path from the behavior module.
https://github.com/autowarefoundation/autoware.universe/blob/69c2a1815034fb53f8c6a1faa5546fb6b49fccff/planning/obstacle_avoidance_planner/src/node.cpp#L1400-L1401

The yaw in the path from the behavior module is not smoothed well. So just resampling cannot deal with smooth yaw interpolation.
You can see how the yaw in the path from the behavior is not smoothed with PathFootprint rviz plugin.

**Comment by angry-crab** [comment]
> @angry-crab obstacle avoidance planner does resampling of x, y, and yaw to the path from the behavior module.
> 
> https://github.com/autowarefoundation/autoware.universe/blob/69c2a1815034fb53f8c6a1faa5546fb6b49fccff/planning/obstacle_avoidance_planner/src/node.cpp#L1400-L1401
> 
> The yaw in the path from the behavior module is not smoothed well. So just resampling cannot deal with smooth yaw interpolation. You can see how the yaw in the path from the behavior is not smoothed with PathFootprint rviz plugin.

Thank you for the information. If so, isn't the unstable output expected somehow? Since this only happens when optimization is skipped, what would be our expectation for resampling methods?

**Comment by angry-crab** [comment]
![skip_optimization_off](https://user-images.githubusercontent.com/93699235/180145614-72b2709d-df9e-4de7-bade-b2d92f3f14bf.png)

![skip_optimization_on](https://user-images.githubusercontent.com/93699235/180145752-f0c5520a-8e73-4cfd-9e8e-a85d24866ea0.png)

**Comment by takayuki5168** [comment]
@angry-crab 
This unstable yaw in the behavior module(?) is not expected. We don't know why this unstable yaw happens. could you look into this issue more. Is this information enough for you to start dealing with this issue?

**Comment by angry-crab** [comment]
@takayuki5168 Thank you for the information. Further investigation indicates that the issue is not related to `obstacle_avoidan
ce_planner`. The output trajectory of `obstacle_avoidance_planner` is as follows:
![interpolate](https://user-images.githubusercontent.com/93699235/180727099-61926f75-576c-48cb-99c8-4d438daca4bf.png)

The plot obtained as @mitsudome-r described is the output of `obstacle_stop_planner`. I'll investigate further. 

> Steps to reproduce:
> 
> * Follow [installation](https://autowarefoundation.github.io/autoware-documentation/main/installation/#installing-autoware) instruction to install Autoware
> * Follow [planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/#planning-simulation) instructions to download the sample map and launch planning simulator.
> * Set current pose and goal pose as shown in the image.
>   ![image](https://user-images.githubusercontent.com/43976834/176368298-7ee7306c-22a4-4a08-af81-efe6b634d71d.png)
> * In rviz display, turn on the debug marker in Planning->ScenarioPlanning->LaneDriving->MotionPlanning->DebugMarker. This will visualize the footprint of the vehicle on the trajectory
>   ![image](https://user-images.githubusercontent.com/43976834/176369089-dc6f29f3-bc60-4195-955a-33f5e2aa347c.png)
> * start rqt_reconfigure
> 
> ```
> source autoware/install/setup.bash
> ros2 run rqt_reconfigure rqt_reconfigure
> ```
> 
> * Type obstacle_avoidance in the filter key and expand to go to the configuration window for the `obstacle_avoidance_planner` node.
>   ![image](https://user-images.githubusercontent.com/43976834/176369603-c86b1dc3-e3bd-4dc9-b37d-5f5e4f17d244.png)
> * tick/untick option.skip_optimization and confirm that footprint is not smooth when skip_optimization is on.
> 
> ![image](https://user-images.githubusercontent.com/43976834/176369521-7f52d96d-322a-4fcc-8622-6a3f85c41590.png)

**Comment by angry-crab** [comment]
FYI, interpolation does not seems good as well. 

![error](https://user-images.githubusercontent.com/93699235/180735751-0816352f-668e-4354-8e64-3d9612764e52.png)

Is this expected? @takayuki5168

**Comment by takayuki5168** [comment]
@angry-crab Not expected.
obstacle_stop_planner is, as you know, after obstacle_avoidance_planner.
When skip_optimization=true, obstacle_avoidance_planner's output is unstable. Therefore obstacle_stop_planner's output is unstable as well. So the problem is obstacle_avoidance_planner (which does fine resampling) or behavior_velocity_planner (which does not do find resampling).

**Comment by angry-crab** [comment]
@takayuki5168 I think the issue is caused by interpolation. I plotted raw interpolated results against original input. 

XY:
![xy](https://user-images.githubusercontent.com/93699235/180949634-93cb180d-22a6-4fea-a97c-5244500409ef.png)

Yaw:
![yaw](https://user-images.githubusercontent.com/93699235/180949668-20088889-0672-49e7-b3af-b4d1eed7045c.png)

X and Y look good, but yaw interpolation is problematic. Is there any specific reason that the interpolation was done for each dimension separately? And do you have any suggestion on how to fix this?

**Comment by takayuki5168** [comment]
@angry-crab Nice plot.
I feel that the problem is yaw of the behavior velocity planner rather than spline interpolation of obstacle avoidance planner.
For example, this yaw of behavior velocity planner (red points plot) is not smooth at all.
Even if we do linear interpolation for yaw in obstacle avoidance planner, the yaw will change a bit suddenly.
![image](https://user-images.githubusercontent.com/20228327/181047595-82efd828-91d0-4a8d-8af8-9e56a72d75df.png)

Could you look into why yaw from behavior velocity planner is not so smoothed?

**Comment by takayuki5168** [comment]
@angry-crab 
I heard that behavior velocity resamples path points with a certain interval and also makes sure that it samples the input path points (path with lane id from behavior_path_planner).

It seems this third red point in the plot is the sampled input path point. This implementation may be wrong
![image](https://user-images.githubusercontent.com/20228327/181147121-03240e03-fc22-41c8-960e-d585c11adb09.png)

**Comment by angry-crab** [comment]
@takayuki5168 Are you suggesting that the implementation of `behavior velocity planner` is wrong because it fails to output a required sampled path, or the implementation of `obstacle_avoidance_planner` is problematic because it could not detect this issue?

**Comment by takayuki5168** [comment]
@angry-crab 

> Are you suggesting that the implementation of behavior velocity planner is wrong

Yes. This is because the behavior velocity planner's output path is not so smooth (Yaw angles change suddenly shown in the plot, which is not expected).

>  or the implementation of obstacle_avoidance_planner is problematic because it could not detect this issue?

For now, no. Because now we do not have a validation mechanism (to detect this issue) in the planning module.

**Comment by angry-crab** [comment]
Further investigatoin indicates that such behavior is caused by interpolation. 
![image](https://user-images.githubusercontent.com/20228327/181147121-03240e03-fc22-41c8-960e-d585c11adb09.png)

When there are two pose really close to each other in Euclidean distance but a somehow large fitting error would lead to such jump in yaw. One example is shown in the following image. 

![??](https://user-images.githubusercontent.com/93699235/181668463-cacfda35-b03f-4dc2-97a9-5bb5260b8ddf.png)

Moreover, unlike `obstacle_avoidance_planner`, `behavior_velocity_planner` interpolates x,y,z, and velocity. Yaw is calculated by `(y[i+1]-y[i])/(x[i+1]-x[i])` 
https://github.com/autowarefoundation/autoware.universe/blob/5571338fd71974b31a51966eb1f8d14bafc48d2e/planning/behavior_velocity_planner/src/utilization/path_utilization.cpp#L236-L240
This is vulnerable to interpolation error and numeric accuracy. Even though the interpolation of x and y look good in picture, tiny horizontal or vertical error would be amplified during calculation when two consecutive poses are too close.  

Some possible ways to fix it:
1. increasing `epsilon` to 0.5 seems to solve the issue. (quick and dirty)
2. linear interpolation. (not differentiable near joints, but should be able to remove the unstable changes)
3. get yaw from vehicle / localization (not sure if it helps or not)
4. 2d pose interpolation with relaxing constraints (does not have to pass the joints)

**Comment by takayuki5168** [comment]
@angry-crab 
Thank you so much for your further investigation.

Could you look into the reason why the yaw of the third red point has an error? I guess if this third red point is removed, the spline interpolation will be stable.
![image](https://user-images.githubusercontent.com/20228327/182069823-65f85fe5-d95e-41dd-8007-83cdbf32ec03.png)

As you know, yaw in the behavior path planner is calculated by x and y. So the reason may be these x and y are not well-smoothed?

**Comment by angry-crab** [comment]
@takayuki5168 
The plotted XY and yaw from `behavior_velocity_planner` is as follows:

XY

![xy_velocity](https://user-images.githubusercontent.com/93699235/182308296-428a1a56-829f-4969-a68d-707be8825178.png)

Yaw(Ignore the last point, it was added to make sure the size of output matches x and y)

![yaw_velocity](https://user-images.githubusercontent.com/93699235/182308332-fc169f3d-9016-4daa-ba7a-bd4ecaf48ae8.png)

From these graphs, we can see that the third yaw is generated by the third and fourth point of interpolated x and y. 
It is true that this part is a little bit concave compared to points in the neighborhood. Again, I believe it is because of interpolation and this kind of error cannot be avoided with interpolation methods. You can see that the input is quite discrete and this gives rise to the interpolated error. I'm not sure how "smooth" we are expecting from interpolation. But the results indicate that it is difficult to expect too much from it.

**Comment by angry-crab** [comment]
After discussing with @takayuki5168 , we believe there is something wrong with the implementation of interpolation because the input points should always overlap with the output points since the original points are kept.

**Comment by angry-crab** [comment]
@takayuki5168 I think the previous error of interpolation we discussed during the meeting is actually caused by plotting.
[error](https://user-images.githubusercontent.com/93699235/182310194-953d98f2-cc1d-42d9-a133-3f8ffebaf5ee.png)
I plotted the points separately and found out that the inputs do exist in the interpolated outputs. The input overlaps with the output as expected. The reason it appears red in the image is because I plotted the input after output.

**Comment by takayuki5168** [comment]
@angry-crab Thank you for your report.
I think now I got the cause.

As shown in the figure, there is a slight difference of s (s is the length along the path) between behavior path points (black ones with a wide interval, input points for spline interpolation) and behavior vel points (red ones, the points with certain interval) since `black l1` is not `red l1 + l2 + l3`.
black a2 and red a4 are the same points, but in the s-x graph, the s is different.
![image](https://user-images.githubusercontent.com/20228327/183321819-c8544dc8-2446-4a9b-a130-7020f77f9a21.png)

**Comment by angry-crab** [comment]
@takayuki5168 Thank you for the graph. Sorry for this late reply because I was off last week. I think the issue is caused by limitation of 1d interpolation. The following plot is y vs s. You could see this is not a "function" because each input s might correspond to two different y. 

![s_y](https://user-images.githubusercontent.com/93699235/184584549-843a5e2c-c16a-4c87-8e81-57b54bb245db.png)

This creates ambiguity when we are looking for intervals to be used for interpolation.

**Comment by angry-crab** [comment]
@takayuki5168 Thank you for the graph. It is truth that the black l1 is shorter than the red segments added up. However, it would not have too much impact on the result because even though a2 and a4 differs, they could just be considered just as different points. Further, the `has_almost_same_value` check is going to add more points anyway. 
Here is another plot. I tried to isolate the interpolation part and created a denser input set to visualize the shape of interpolation function. Red points are generated with a step size of 0.1. 
![Figure_20](https://user-images.githubusercontent.com/93699235/184806761-8be6efd9-9e01-486d-992a-0d4b99b22b62.png)

1. I think the interpolation itself is good. I also tried to create artificial inputs with random noises to see its fault tolerance. If the random noise is within 0.1, the output looks good. 
2. I feel it is difficult to go further with removing certain points.
3. Back to our original problem, I guess there are two ways that I can think of to solve the issue. (1. keep a certain distance between consecutive poses. 2. Don't interpolate yaw, calculate it instead with consecutive poses in `behavior_avoidance_planner`. )

Please let me know your thoughts on this.

**Comment by takayuki5168** [comment]
@angry-crab 
Seeing this plot, I remembered that matplotlib discretized the large values when plotting. We can see that some successive red points have the same value, and that's what I said.
![image](https://user-images.githubusercontent.com/20228327/185301411-de54d5a9-bdcc-4dbf-ad1b-631dba590bb6.png)

In this plot, the same matplotlib issue may occur.
I mean, the second red point and the second green point seem to have to same value which we considered as the problem, but 
 I guess these points does not have the same value.
![image](https://user-images.githubusercontent.com/20228327/185301990-697772fe-d54b-4726-8b93-70ba46e035f5.png)

**Comment by takayuki5168** [comment]
However, as you pointed in this plot, there still is the issue of interpolation error.
![image](https://user-images.githubusercontent.com/20228327/185302656-e29c75eb-4969-4da8-b608-50f30ef0cc0c.png)

**Comment by angry-crab** [comment]
After discussing with @takayuki5168, I believe the issue is due to pairs of poses that are too close in distance, especially near the input poses of interpolation. Since interpolation forces the second derivative at input pose to be zero, close pairs of poses are assigned similar values. This fact give rise to a sudden change in yaw for the next consecutive poses.

**Comment by angry-crab** [comment]
In conclusion, adjusting `epsilon` solves the issue. Setting `epsilon = 0.2`, we have the following trajectory. 
![epsilon](https://user-images.githubusercontent.com/93699235/186072896-56f1d55e-f3d9-4702-b594-da4836d33ca0.png)

**Comment by angry-crab** [comment]
#1687 
This PR fixes the issue somehow, but it is correcting the yaw afterwards.
